---
- name: "[Config][Tmux] Configure .tmux.conf"
  vars:
    app: Tmux
    source_file: tmux.conf
    target_file: "{{ ansible_env.HOME }}/.tmux.conf"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml

# TODO: Add changed_when/failed_when
- name: "[Config][Tmux] Install plugins" # noqa no-changed-when
  ansible.builtin.command: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/install_plugins"

# TODO: Add changed_when/failed_when
- name: "[Config][Tmux] Update plugins" # noqa no-changed-when
  ansible.builtin.command: "{{ ansible_env.HOME }}/.tmux/plugins/tpm/bin/update_plugins all"

- name: "[Config][Tmuxp] Create directory in {{ ansible_env.HOME }}/.tmuxp"
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.tmuxp"
    state: directory
    mode: '0755'

- name: "[Config][Tmuxp] Check for existing files in {{ ansible_env.HOME }}/.tmuxp"
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.tmuxp"
    file_type: file
    recurse: no
    hidden: true
  register: tmuxp_existing_files
  changed_when: false

- name: "[Config][Tmuxp] Add default session file"
  vars:
    app: Tmuxp
    source_file: tmuxp-default.yaml
    target_file: "{{ ansible_env.HOME }}/.tmuxp/default_session.yaml"
  ansible.builtin.include_role:
    name: common
    tasks_from: config_file.yml
  when: tmuxp_existing_files.matched | default(0) == 0
