---
- name: "[{{ app }}] Save version to `current-versions.yml`"
  ansible.builtin.shell: |
    set -e -o pipefail
    yq -i '{{ yq_query }}' {{ playbook_dir }}/../current-versions.yml
  args:
    executable: /bin/bash
  changed_when: false

- name: "[{{ app }}] Save version to ansible fact"
  ansible.builtin.set_fact:
    current_versions: "{{ current_versions | combine(target_version, list_merge='append', recursive=true) }}"
