# FD - fast and user-friendly alternative to find
# Source: https://github.com/sharkdp/fd
---
- name: "[FD] Check if Ubuntu native fd-find is installed"
  ansible.builtin.command: dpkg-query -W fd-find
  register: fd_find_check_deb
  ignore_errors: true
  changed_when: fd_find_check_deb.rc > 1
  failed_when: fd_find_check_deb.rc > 1

- name: "[FD] Remove fd-find Ubuntu package"
  ansible.builtin.apt:
    name: fd-find
    state: absent
  become: true
  when: fd_find_check_deb.rc == 0

- name: "[FD] Check installed FD version"
  ansible.builtin.command: dpkg-query -W fd
  register: fd_check_deb
  ignore_errors: true
  changed_when: fd_check_deb.rc > 1
  failed_when: fd_check_deb.rc > 1
  tags:
    - versions

- name: "[FD] Get Github URL for proper version"
  vars:
    app: fd
    repo: sharkdp/fd
    version_query: curl -s https://api.github.com/repos/sharkdp/fd/releases/latest | jq .name -r | cut -f2 -d'v'
    github_uri: v{{ fd_version }}/fd_{{ fd_version }}_amd64.deb
  ansible.builtin.include_role:
    name: common
    tasks_from: github_version.yml
    apply:
      tags:
        - versions
  tags:
    - versions

- name: "Installation"
  when: fd_check_deb.stdout | regex_search('[0-9]+\.[0-9]+\.[0-9]+') | default(0) != fd_version
  block:
    - name: "[FD] Create directory in {{ ansible_env.HOME }}/.local/opt"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/opt/fd-{{ fd_version }}"
        state: directory
        mode: '0755'

    - name: "[FD] Download FD {{ fd_version }}"
      ansible.builtin.get_url:
        url: "{{ fd_url }}"
        dest: "{{ ansible_env.HOME }}/.local/opt/fd-{{ fd_version }}"
        mode: '0755'

    - name: "[FD] Install {{ fd_version }} .deb package"
      ansible.builtin.apt:
        deb: "{{ ansible_env.HOME }}/.local/opt/fd-{{ fd_version }}/fd_{{ fd_version }}_amd64.deb"
      become: true

- name: "[fd] Save used version"
  vars:
    app: fd
    target_version:
      github_packages:
        fd: "{{ fd_version }}"
    yq_query: ".github_packages.fd = \"{{ fd_version }}\""
  ansible.builtin.include_role:
    name: common
    tasks_from: save_version.yml
    apply:
      tags:
        - versions
  tags:
    - versions
