# Helm 3 Kubernetes package manager
#
# Sources:
#  - https://helm.sh/
#  - https://github.com/helm/helm
---
- name: "[Helm] Get Github URL for proper version"
  vars:
    app: helm
    repo: helm/helm
    version_query: curl -s https://api.github.com/repos/helm/helm/releases/latest | jq .name -r | cut -f2 -d'v' | grep -Po '\d+\.\d+\.\d+\.?\d?'
    artifact_url: https://get.helm.sh/helm-v{{ helm_version }}-linux-amd64.tar.gz
  ansible.builtin.include_role:
    name: common
    tasks_from: github_version.yml
    apply:
      tags:
        - versions
  tags:
    - versions

- name: "[Helm] Check if Helm {{ helm_version }} is installed"
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/opt/helm-{{ helm_version }}"
  register: helm_dir

- name: "Installation"
  when: not helm_dir.stat.exists
  block:
    - name: "[Helm] Download Helm {{ helm_version }}"
      ansible.builtin.get_url:
        url: "{{ helm_url }}"
        dest: "/tmp/helm-{{ helm_version }}.tar.gz"
        mode: '0755'

    - name: "[Helm] Create directory in {{ ansible_env.HOME }}/.local/opt"
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/opt/helm-{{ helm_version }}"
        state: directory
        mode: '0755'

    - name: "[Helm] Untar archive"
      ansible.builtin.unarchive:
        src: "/tmp/helm-{{ helm_version }}.tar.gz"
        dest: "{{ ansible_env.HOME }}/.local/opt/helm-{{ helm_version }}"

    - name: "[Helm] Cleanup tar.gz file"
      ansible.builtin.file:
        path: "/tmp/helm-{{ helm_version }}.tar.gz"
        state: absent

- name: "[Helm] Link {{ helm_version }} binary"
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/opt/helm-{{ helm_version }}/linux-amd64/helm"
    dest: "{{ ansible_env.HOME }}/.local/bin/helm"
    state: link
    force: true

- name: "[helm] Save used version"
  vars:
    app: helm
    target_version:
      github_packages:
        helm: "{{ helm_version }}"
    yq_query: ".github_packages.helm = \"{{ helm_version }}\""
  ansible.builtin.include_role:
    name: common
    tasks_from: save_version.yml
    apply:
      tags:
        - versions
  tags:
    - versions
