---
# Add this variable to your ansible/vars/overrides.yml if needed
# This is array of tasks to exclude from software role.
# For list of tasks see: software/tasks/main.yml or see README.md
software_tasks_exclude: []
# System manager to use. Ansible has issues detecting SysV vs. SystemD on WSL distributions
# If you are using SysVInit WSL (not recommended, see `README.md`), overwrite this in `ansible/vars/overrides.yml` to `sysvinit`
service_manager: systemd
# Default packages to be installed first, using APT
# There is no version here as those are Ubuntu distro defaults always
default_apt_packages:
  - curl
  - unzip
  - plocate
  - tree
  - htop
  - jq
  - gcc
  - zip
  - dos2unix
  - php
  - composer
  - keychain
    #  - exa # Used in fzf-tab
  - bc # Required for git commands in cmdline
  - libfuse2 # Required for Neovim Appimage
  - groff # Required for AWS CLI
  - libevent-dev # Required for latest Tmux install
  - universal-ctags # Required for latest Tmux install
  - ncurses-dev # Required for latest Tmux install
  - ca-certificates # Required for Azure CLI
  - apt-transport-https # Required for Azure CLI
  - lsb-release # Required for Azure CLI
  - gnupg # Required for Azure CLI
  - make # Required for GVM
  - binutils # Required for GVM
  - bison # Required for GVM
  - build-essential # Required for GVM
  - mercurial # Required for GVM
  - fswatch
  - gdu
  - gh
  - bat
  - luarocks
  - lua5.4
# Specific versions for software (github)
# Fixed versions should be set without `v` prefix (e.g: 1.4.3)
github_packages:
  neovim: latest # Gets latest tag. Set to `nightly` for latest nightly (not recommended)
  diff_so_fancy: latest
  zoxide: latest
  helm: latest
  lazygit: latest
  fzf: latest
  tmux: "latest"
  ripgrep: latest
  fd: latest
  kind: latest
  k9s: latest
  yq: latest
  win32yank: latest
  terraform: latest
  terragrunt: latest
  bottom: 0.10.2
  git_fuzzy: latest # Does not have releases, latest (for latest commit) or specific commit
  nvm: latest # Node Version Manater
  tpm: latest # Tmux plugin manager. Does not have releases, gets latest tag instead
  pes: latest # Puppet Editor Services. They don't release anymore, so latest means latest commit
  p10k: latest
  rvm1_ansible: 2.2.0 # Version of https://github.com/rvm/rvm1-ansible
  pay_respects: latest
  kubeswitch: latest
# Kubectl version
kubectl_version: latest
# Packages and their versions to install with PIP
pip_packages:
  gita: latest
  tmuxp: 1.34.0
  az_account_switcher: latest
  # thefuck: "latest"
# FZF
fzf_git_url: "https://github.com/junegunn/fzf.git"
fzf_home: "{{ ansible_env.HOME }}/.fzf"
# Git from custom PPA repo
git_apt_version: latest
# GIT Fuzzy
git_fuzzy_url: "https://github.com/bigH/git-fuzzy.git"
git_fuzzy_home: "{{ ansible_env.HOME }}/.local/opt/git-fuzzy"
# Oh-My-Zsh
omz_home: "{{ ansible_env.HOME }}/.oh-my-zsh"
omz_plugins:
  fzf-tab: https://github.com/Aloxaf/fzf-tab
  fzf-tab-source: https://github.com/Freed-Wu/fzf-tab-source.git
  k: https://github.com/supercrabtree/k
  you-should-use: https://github.com/MichaelAquilina/zsh-you-should-use.git
  zsh-autosuggestions: https://github.com/zsh-users/zsh-autosuggestions
  zsh-syntax-highlighting: https://github.com/zsh-users/zsh-syntax-highlighting.git
  zsh-sdkman: https://github.com/matthieusb/zsh-sdkman.git
  zsh-lazyload: https://github.com/qoomon/zsh-lazyload
  pyenv-lazy: https://github.com/davidparsson/zsh-pyenv-lazy.git
  zsh-snv: https://github.com/rpeshkov/zsh-snv
  jq: https://github.com/reegnz/jq-zsh-plugin.git
# TMUX Plugin Manager
tmux_plugins_dir: "{{ ansible_env.HOME }}/.tmux/plugins"
tpm_git_url: https://github.com/tmux-plugins/tpm.git
# Docker system dependency packages
docker_apt_dependencies:
  - ca-certificates
  - gnupg
  - lsb-release
# Docker main packages from APT repo
docker_apt_packages:
  docker-ce: latest
  docker-compose-plugin: latest
  containerd.io: latest
# RVM / Ruby
rvm1_rubies:
  - ruby-3.3.4
rvm1_user: "{{ ansible_user_id }}"
# Ruby
# Install any gem for any ruby. `all` installs for all of them
# Note that if Puppet is installed, it will install puppet/puppet-lint gems, so no need to add here.
# Specific ruby must match one from `rvm_rubies` list (see OS-specific vars file)
# You need to set specific gem version, `latest` is not supported here
ruby_gems:
  - ruby: all
    gems:
      - neovim: 0.10.0
# Puppet
puppet_version: 8.4.0
puppet_lint_version: 4.2.3
puppet_rubies:
  - all # to install only for specific rubies, list their names (must match `rvm1_rubies`)
# Example:
# puppet_rubies:
#   - ruby-2.7.6
#   - ruby-3.1.2

# PDK (Puppet Development KIT)
# Please note the module does not support package downgrades - if PDK is already installed in higher version, remove it first.
puppet_pdk_version: latest
# Node
node_version: "lts/iron"
npm_default_packages:
  - tree-sitter-cli
  - neovim
  - vscode-langservers-extracted
# Ansible
ansible_pip_version: latest
ansible_lint_pip_version: latest
# LunarVIM
lunarvim_remove: true
# Azure CLI
azurecli_apt_version: latest
# AWS CLI
awscli_url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
# Puppet
puppet_pes_url: https://github.com/puppetlabs/puppet-editor-services.git
# SDK Man
sdkman_update: true
sdkman_user: "{{ ansible_user_id }}"
sdkman_group: "{{ ansible_user_gid }}"
sdkman_user_home_dir: "{{ ansible_env.HOME }}"
sdkman_dir: "{{ sdkman_user_home_dir + '/.sdkman' }}"
sdkman_tmp_dir: /tmp
sdkman_validate_ssl: true
sdkman_install_packages:
  - candidate: java
    version: 18.0.2-open
  - candidate: java
    version: 21.0.2-open
  - candidate: gradle
    version: 8.5
  - candidate: groovy
    version: 4.0.18
  - candidate: maven
    version: 3.9.6
sdkman_uninstall_packages: []
# sdkman_uninstall_packages:
#   - { candidate: java, version: 6u45 }
# Configure default candidate versions
sdkman_defaults:
  java: "21.0.2-open"
  gradle: "8.5"
  groovy: "4.0.18"
  maven: "3.9.6"
# Flush caches before/after installing SDK packages
# Reference: http://sdkman.io/usage (Flush section)
sdkman_flush_caches_before: []
sdkman_flush_caches_after: []
# Link SDKMAN installed packages
# Reference: https://linux.die.net/man/8/update-alternatives
sdkman_update_alternatives: []
# Go versions installed with GVM
go_versions:
  - go1.21.6
go_default: go1.21.6

rvm1_gpg_key_servers:
  - hkp://keys.openpgp.org
